var classTypes = {
    dk: {
        blood: [
            ["Head", 40554, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ],
        frost: [
            ["Head", 51280, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ],
        unholy: [
            ["Head", 51281, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ]
    },
    mage: {
        arcane: [
            ["Head", 51280, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ],
        fire: [
            ["Head", 51281, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ],
        frost: [
            ["Head", 40554, null, null],
            ["Neck", null, null, null],
            ["Sholder", null, null, null],
            ["Cape", null, null, null],
            ["Wrist", null, null, null],
            ["Hands", null, null, null],
            ["Legs", null, null, null],
            ["Feet", null, null, null],
            ["Ring", null, null, null],
            ["Ring", null, null, null],
            ["Trinket", null, null, null],
            ["Trinket", null, null, null],
            ["Main Hand", null, null, null],
            ["Off Hand", null, null, null],
            ["Relic", null, null, null],
        ]
    }
};
